# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

Rake::TestTask.new(:test_unit_webrat => "db:test:prepare") do |t|
  ENV['WEBRAT_INTEGRATION_MODE'] = 'webrat'
  t.libs << "test"
  t.pattern = 'test/integration/**/*_test.rb'
  t.verbose = true
end
Rake::Task['test_unit_webrat'].comment = "runs the test::unit based tests in webrat mode"

Rake::TestTask.new(:test_unit_selenium => "db:test:prepare") do |t|
  ENV['WEBRAT_INTEGRATION_MODE'] = 'selenium'
  t.libs << "test"
  t.pattern = 'test/integration/**/*_test.rb'
  t.verbose = true
end
Rake::Task['test_unit_selenium'].comment = "runs the test::unit based tests in selenium mode"