# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

desc "runs the test::unit based tests in webrat mode"
task :test_unit_webrat do
  ENV['WEBRAT_INTEGRATION_MODE'] = 'webrat'
  Rake::Task['test:integration'].invoke
end

desc "runs the test::unit based tests in selenium mode"
task :test_unit_webrat do
  ENV['WEBRAT_INTEGRATION_MODE'] = 'selenium'
  Rake::Task['test:integration'].invoke
end
